# This is a basic workflow to help you get started with Actions

name: Gihub Actions Maven Build Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # setup JFrog CLI
      - name: Step 1-  Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_RT_EP }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 2-  Checkout main branch from Github
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step3 - Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Runs a set of commands using the runners shell
      - name: Step4 - Have Gibub Actions build Maven Project
        run: |
          # Build
          jfrog rt mvn -B package --file pom.xml
          # Get the java-version
          version=$(./jfrog -v | cut -d " " -f 3)
          echo Build JFrog CLI version $version
          # Upload the jfrog-cli binary
          jfrog rt u jfrog backend-libs-snapshot-local/jfrog-cli-releases/$version/
          # Add env vars
          jfrog rt bce
          #Publish build-info
          jfrog rt bp 
          # Scan build with JFrog Xray
          jfrog rt bs --fail=false > out.txt
          # Update the PR comment
          gh pr comment --body-file out.txt



      - name: Step5 - list files
        run: ls  -a
        
      - name: Step6 - What is in target folder
        run: |
           cd target
           ls  -a       
